### ISSUE TITLE
[Task] Implement Plugins Page

### ISSUE THREAD

**Issue by tjtanjin** [React-ChatBotify/gallery-website#59]
**Task Description:**
Implement the Plugins page

**Deliverable(s):**
Implement the plugins page according to design specs that is well-styled, responsive, and adheres to the correct folder structure.

**Additional Context:**
The Plugins page mockup can be found on [mockup](https://www.figma.com/design/oK12zZACqvlACoqkZIrtxV/Gallery-Website?node-id=2545-3326&node-type=section)

**Comment by hunxjunedo** [comment]
@HusseinSerag what is the progress of this one ? do we atleast have a hook prepared to fetch the plugins ?
