### ISSUE TITLE
[Feat] Re-design the themes preview pane with animation

### ISSUE THREAD

**Issue by hunxjunedo** [React-ChatBotify/gallery-website#77]
this is really bad UI right now, re-design it with a nice animation on Figma.

**Comment by Deksu** [comment]
@hunxjunedo Sorry for late reply, been sick this past week. Anyway, I'm not entirely sure what the themes preview pane is referring to here. Easier for me personally to follow tasks/requests etc. via Figma comments or Discord: feel free to DM me there.

**Comment by hunxjunedo** [comment]
Solved: https://www.figma.com/proto/oK12zZACqvlACoqkZIrtxV/Gallery-Website?page-id=75%3A2347&node-id=2567-14290&node-type=frame&viewport=122%2C-5192%2C0.19&t=H9xeJRpv3K9H6lsa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2567%3A12705
